spring.application.name=taskflow-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=taskflow_user
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
